/**
 * TraceMemo domain types.
 *
 * Pure TypeScript types only - no runtime dependencies. Runtime validation
 * lives in `../validation/index.ts`, account-key helpers in `./account.ts`,
 * and field limits in `../limits.ts`.
 *
 * Address identity is chain-aware (docs/01-PRD.md, 02-TECHNICAL-ARCHITECTURE.md
 * section 6). Ethereum Mainnet (chain id 1) and Base (chain id 8453) are
 * distinct research subjects: the same 0x address on each chain is NOT auto-
 * merged. The canonical key is `eip155:<chainId>:<lowercase address>`.
 */

/** Supported EVM chain ids. Ethereum Mainnet and Base only for MVP. */
export type SupportedChainId = 1 | 8453;

/** Canonical, chain-aware account key: `eip155:<chainId>:<lowercase address>`. */
export type AccountKey = `eip155:${SupportedChainId}:${string}`;

/** A 20-byte EVM address in 0x hexadecimal form. */
export type EvmAddress = `0x${string}`;

/** User-assigned confidence in an attribution. */
export type Confidence = 'confirmed' | 'likely' | 'unverified';

/** Supported explorer site identifiers. */
export type SiteId = 'etherscan' | 'basescan';

/** A persisted source backing a record's conclusion. */
export interface ResearchSource {
  id: string;
  url: string;
  title: string;
  createdAt: string;
}

/**
 * Source input authored by the UI. The `id` and `createdAt` are generated by
 * the background (never trusted from the client), so the UI submits only
 * `url` and `title`.
 */
export interface SourceInput {
  url: string;
  title: string;
}

/** A persisted research record for one account on one chain. */
export interface AddressRecord {
  key: AccountKey;
  chainId: SupportedChainId;
  address: EvmAddress;
  label: string;
  note: string;
  confidence: Confidence;
  sources: ResearchSource[];
  createdAt: string;
  updatedAt: string;
}

/** DTO for creating a record. The background derives key, timestamps, source ids. */
export interface RecordCreateInput {
  chainId: SupportedChainId;
  address: EvmAddress;
  label: string;
  note: string;
  confidence: Confidence;
  sources: SourceInput[];
}

/** DTO for updating an existing record. The address/chain are immutable. */
export interface RecordUpdateInput {
  key: AccountKey;
  label: string;
  note: string;
  confidence: Confidence;
  sources: SourceInput[];
}

/** Page context as authored by the content script. No tabId: the background
 * takes the real tab id from MessageSender.tab.id and never trusts client input. */
export interface PageContextInput {
  tabUrl: string;
  pageTitle: string;
  site: SiteId;
  chainId: SupportedChainId;
  accountKeys: AccountKey[];
  observedAt: string;
}

/** Stored page context for one tab. */
export interface PageContext extends PageContextInput {
  tabId: number;
}

/** Small settings persisted via chrome.storage (not IndexedDB). */
export interface Settings {
  annotationsEnabled: boolean;
  onboardingSeen: boolean;
}

/** Versioned export envelope. */
export interface TraceMemoExport {
  format: 'tracememo';
  version: 1;
  exportedAt: string;
  records: AddressRecord[];
}

/** Counts returned by an import write operation. */
export interface ImportResult {
  created: number;
  updated: number;
  skipped: number;
  invalid: number;
}

/** Counts returned by an import dry-run preview (no writes). */
export interface ImportPreview {
  total: number;
  created: number;
  updated: number;
  skipped: number;
}

/** Default settings used on first install. */
export const DEFAULT_SETTINGS: Settings = {
  annotationsEnabled: true,
  onboardingSeen: false,
};
